version: '3.8'
services:
    back-end-covid:
        build: .
        container_name: api-covid
        depends_on: 
            - mongo-covid
        volumes:
            - .:/app
        ports: 
            - 8080:8080
        links: 
            - mongo-covid
    mongo-covid:
        image: mongo:bionic
        container_name: mongo-db-covid
        restart: always
        ports:
            - 27017:27017
        
